/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import connection.DB;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
/**
 *
 * @author M A Z A
 */
public class MasterForm extends javax.swing.JFrame {
private DefaultTableModel tabMode;
private Connection con = new DB().connect();

    /**
     * 
     * Creates new form MasterForm
     */
    public MasterForm() {
        initComponents();
        dataTable();
    }
    protected void clearInput(){
        idLabel.setText("None");
        DrugCode.setText("");
        DrugName.setText("");
        uomInput.setText("");
        stockInput.setText("");
        buyPrice.setText("");
        sellPrice.setText("");
    }
    protected void dataTable(){
        Object[] row = {"id","code","drug_name","Drug_Category","uom","buy_price","sell_price","stock"};
        tabMode = new DefaultTableModel(null, row);
        String search = searchData.getText();
        
        try{
            String sqlSearch = "SELECT * FROM drug where drug_name like '%"+search+"%' or drug_category like '%"+search+"%' order by id asc";
            Statement stat = con.createStatement();
            ResultSet res = stat.executeQuery(sqlSearch);
            while (res.next()){
          tabMode.addRow(new Object[]{
          res.getString(1),
          res.getString(2),
          res.getString(3),
          res.getString(4),
          res.getString(5),
          res.getString(6),
          res.getString(7),
          res.getString(8),
       });
      }
            
        DrugTable.setModel(tabMode);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Failure ocurred: "+e);
        }
    }
    
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name_Info = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DrugTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DrugCode = new javax.swing.JTextField();
        DrugName = new javax.swing.JTextField();
        buyPrice = new javax.swing.JTextField();
        sellPrice = new javax.swing.JTextField();
        stockInput = new javax.swing.JTextField();
        DrugCategory = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        clearInputBtn = new javax.swing.JButton();
        searchData = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        uomInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Name_Info.setText("202043502732 - Muhammad Alif Zhorif Arachdin");

        DrugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        DrugTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                DrugTableComponentAdded(evt);
            }
        });
        DrugTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DrugTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DrugTable);

        jLabel1.setText("Drug Code");

        jLabel2.setText("Drug Name");

        jLabel3.setText("Drug Category");

        jLabel4.setText("Buying Price");

        jLabel5.setText("Selling Price");

        jLabel6.setText("Stock");

        stockInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockInputActionPerformed(evt);
            }
        });

        DrugCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hormone", "Fever", "Medicine", "Syrup", "Tablet", "Other" }));
        DrugCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrugCategoryActionPerformed(evt);
            }
        });

        addBtn.setText("Add new");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        clearInputBtn.setText("Clear Input");
        clearInputBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearInputBtnActionPerformed(evt);
            }
        });

        searchData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchDataKeyPressed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Selected ID");

        idLabel.setText("None");
        idLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                idLabelComponentShown(evt);
            }
        });

        uomInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uomInputActionPerformed(evt);
            }
        });

        jLabel8.setText("Unit of Measurement");

        refreshBtn.setText("Refresh Table");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Name_Info)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(8, 8, 8))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DrugCode, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DrugName, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DrugCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stockInput, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uomInput, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchData, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearInputBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Name_Info)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(deleteBtn))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateBtn)
                            .addComponent(clearInputBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(idLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(DrugCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(DrugName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(DrugCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(buyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(stockInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uomInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(refreshBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DrugTableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_DrugTableComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_DrugTableComponentAdded

    private void DrugCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrugCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrugCategoryActionPerformed

    private void stockInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockInputActionPerformed

    
    private void idLabelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_idLabelComponentShown
//        newLabel = new JLabel("0");
//        idLabel.setText(newLabel.getText());
    }//GEN-LAST:event_idLabelComponentShown

    private void clearInputBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearInputBtnActionPerformed
       clearInput();
    }//GEN-LAST:event_clearInputBtnActionPerformed
    
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        //event when cliking add new button
        String sqlAdd = "INSERT INTO drug values(null,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = con.prepareStatement(sqlAdd);
            stat.setString(1, DrugCode.getText());
            stat.setString(2, DrugName.getText());
            stat.setString(3, DrugCategory.getSelectedItem().toString());
            stat.setString(4, uomInput.getText());
            stat.setString(5, buyPrice.getText());
            stat.setString(6, sellPrice.getText());
            stat.setString(7, stockInput.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Insertion Complete");
            stat.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data insertion Failed: "+e);
        }
        dataTable();
        clearInput();
    }//GEN-LAST:event_addBtnActionPerformed

    private void uomInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uomInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uomInputActionPerformed

    private void DrugTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrugTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = DrugTable.getSelectedRow();
        String id = tabMode.getValueAt(selectedRow, 0).toString();
        String code = tabMode.getValueAt(selectedRow, 1).toString();
        String name = tabMode.getValueAt(selectedRow, 2).toString();
        String category = tabMode.getValueAt(selectedRow, 3).toString();
        String uom = tabMode.getValueAt(selectedRow, 4).toString();
        String buy = tabMode.getValueAt(selectedRow, 5).toString();
        String sell = tabMode.getValueAt(selectedRow, 6).toString();
        String stock = tabMode.getValueAt(selectedRow, 7).toString();
        idLabel.setText(id);
        DrugCode.setText(code);
        DrugName.setText(name);
        DrugCategory.setSelectedItem(category);
        uomInput.setText(uom);
        buyPrice.setText(buy);
        sellPrice.setText(sell);
        stockInput.setText(stock);
        
        
        
        
    }//GEN-LAST:event_DrugTableMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String id = idLabel.getText();
        
        if(id == "None"){
            JOptionPane.showMessageDialog(null, "Failed To Update: ID value is None");
        }
        
        String sqlEdit = "UPDATE drug Set code=?, drug_name=?, drug_category=?, uom=?, buy_price=?, sell_price=?, stock=? WHERE id='"+id+"'";
        try{
            PreparedStatement stat = con.prepareStatement(sqlEdit);
            stat.setString(1, DrugCode.getText());
            stat.setString(2, DrugName.getText());
            stat.setString(3, DrugCategory.getSelectedItem().toString());
            stat.setString(4, uomInput.getText());
            stat.setString(5, buyPrice.getText());
            stat.setString(6, sellPrice.getText());
            stat.setString(7, stockInput.getText());
            stat.executeUpdate();
            if(id != "None"){
                JOptionPane.showMessageDialog(null, "Data Update Complete");
            }
            stat.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data Update Failed: "+e);
        }
        dataTable();
        clearInput();
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String id = idLabel.getText();
        int confirmed = JOptionPane.showConfirmDialog(null,"Delete","Confirm Dialog",JOptionPane.YES_NO_OPTION);
        if(confirmed == 0 && id != "None"){
            try{
                String sqlDelete = "DELETE FROM drug WHERE id='"+id+"'";
                PreparedStatement stat = con.prepareStatement(sqlDelete);
                stat.executeUpdate();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data Deletion Failed: "+e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Deletion Failed: ID value is none");
        }
        dataTable();
        clearInput();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchDataKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            dataTable();
        }
    }//GEN-LAST:event_searchDataKeyPressed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        dataTable();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        searchData.setText("");
        dataTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DrugCategory;
    private javax.swing.JTextField DrugCode;
    private javax.swing.JTextField DrugName;
    private javax.swing.JTable DrugTable;
    private javax.swing.JLabel Name_Info;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField buyPrice;
    private javax.swing.JButton clearInputBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchData;
    private javax.swing.JTextField sellPrice;
    private javax.swing.JTextField stockInput;
    private javax.swing.JTextField uomInput;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
